/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.v7.recyclerview;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f040027;
        public static final int coordinatorLayoutStyle = 0x7f0400a4;
        public static final int fastScrollEnabled = 0x7f0400d0;
        public static final int fastScrollHorizontalThumbDrawable = 0x7f0400d1;
        public static final int fastScrollHorizontalTrackDrawable = 0x7f0400d2;
        public static final int fastScrollVerticalThumbDrawable = 0x7f0400d3;
        public static final int fastScrollVerticalTrackDrawable = 0x7f0400d4;
        public static final int font = 0x7f0400d7;
        public static final int fontProviderAuthority = 0x7f0400d9;
        public static final int fontProviderCerts = 0x7f0400da;
        public static final int fontProviderFetchStrategy = 0x7f0400db;
        public static final int fontProviderFetchTimeout = 0x7f0400dc;
        public static final int fontProviderPackage = 0x7f0400dd;
        public static final int fontProviderQuery = 0x7f0400de;
        public static final int fontStyle = 0x7f0400df;
        public static final int fontVariationSettings = 0x7f0400e0;
        public static final int fontWeight = 0x7f0400e1;
        public static final int keylines = 0x7f04010d;
        public static final int layoutManager = 0x7f040111;
        public static final int layout_anchor = 0x7f040112;
        public static final int layout_anchorGravity = 0x7f040113;
        public static final int layout_behavior = 0x7f040114;
        public static final int layout_dodgeInsetEdges = 0x7f040140;
        public static final int layout_insetEdge = 0x7f040149;
        public static final int layout_keyline = 0x7f04014a;
        public static final int reverseLayout = 0x7f040185;
        public static final int spanCount = 0x7f04019a;
        public static final int stackFromEnd = 0x7f0401a0;
        public static final int statusBarBackground = 0x7f0401a6;
        